# The character that should surround emoji names. E.g. the emoji :smile: uses the character :
EmojiTag: ":"

# Defines translation of emojis to unicodes
Emoji:
  "\ue000": matsuri_pog
  "\ue001": ayame_despair
  "\ue002": omegapol
  "\ue003": ina_humu

# Each group defines allowed unicodes.
Groups:
  default:
    - "\ue000"
    - "\ue001"
    - "\ue002"
  admin:
    - "\ue100:\ue105"
