# The character that should surround emoji names. E.g. the emoji :smile: uses the character :
EmojiTag: ":"

# Defines translation of emojis to unicodes
Emoji:
  e000: matsuri_pog
  e001: ayame_despair
  e002: omegapol
  e003: ina_humu

# Each group defines allowed unicodes.
Groups:
  default:
    - e000
    - e001
    - e002
  admin:
    - e100:e105
